version: '3.7'

services:
  logstash:
    build: ./logstash/
    restart: always
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
      - COUCHDB_HOST=${COUCHDB_HOST}
      - COUCHDB_PORT=${COUCHDB_PORT}
      - COUCHDB_SEQ=/tmp/couchdb/sequence_path.txt
      - COUCHDB_SECURE=${COUCHDB_SECURE:-true}
      - HTTP_ENDPOINT=postgrest:3000

  superset:
    build: 
      context: ./superset/
      args:
        SUPERSET_PASSWORD: ${SUPERSET_PASSWORD:-password}
        SUPERSET_ADMIN_EMAIL: ${SUPERSET_ADMIN_EMAIL:-user@superset.com}
    ports:
      - 8080:8088

  dbt:
    platform: linux/amd64
    image: medicmobile/dataemon:latest
    environment:
      - POSTGRES_HOST=${DBT_POSTGRES_HOST}
      - POSTGRES_USER=${DBT_POSTGRES_USER}
      - POSTGRES_PASSWORD=${DBT_POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_TABLE=${POSTGRES_TABLE}
      - POSTGRES_SCHEMA=${DBT_POSTGRES_SCHEMA}
      - ROOT_POSTGRES_SCHEMA=${POSTGRES_SCHEMA}
      - DATAEMON_INITAL_PACKAGE=${CHT_PIPELINE_BRANCH_URL}

  metabase:
    image: metabase/metabase
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: data
      MB_DB_PORT: 5432
      MB_DB_USER: ${POSTGRES_USER}
      MB_DB_PASS: ${POSTGRES_PASSWORD}
      MB_DB_HOST: postgres
    ports:
       - 3001:3000
